name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Aleks"

      # Install Dependencies
      - name: Install Dependencies
        run: npm install
      # Linting
      - name: Lint Code
        run: npm run lint
      # Testing
      - name: Unit Test
        run: npm run test
      # Build
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@main
        with:
          name: my-artifact
          path: public/
      - uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE }}
